const INVESTING_IL = 'https://il.investing.com';

const MACRO_RESEARCH_RESOURCES = Object.freeze([
  Object.freeze({
    key: 'economic-calendar',
    labelHe: 'יומן כלכלי',
    descriptionHe: 'אירועים קרובים, נתון בפועל, צפי ונתון קודם',
    provider: 'Investing.com Israel',
    url: `${INVESTING_IL}/economic-calendar/`,
    icon: '📅',
    category: 'events',
    external: true,
  }),
  Object.freeze({
    key: 'fedwatch',
    labelHe: 'צפי ריבית הפד',
    descriptionHe: 'הסתברויות השוק לשינוי בריבית בהחלטות הפד הקרובות',
    provider: 'CME Group',
    url: 'https://www.cmegroup.com/en/markets/interest-rates/cme-fedwatch-tool.html',
    icon: '🏦',
    category: 'rates',
    external: true,
  }),
  Object.freeze({
    key: 'us-10y',
    labelHe: 'אג״ח ארה״ב 10 שנים',
    descriptionHe: 'תשואת האג״ח הממשלתית, השינוי והגרף',
    provider: 'Investing.com Israel',
    url: `${INVESTING_IL}/rates-bonds/u.s.-10-year-bond-yield`,
    icon: '📈',
    category: 'yield',
    external: true,
    canonicalIdentity: 'BONDS10Y',
    aliases: Object.freeze(['BONDS10Y', 'US10Y', 'TNX']),
  }),
  Object.freeze({
    key: 'vix',
    labelHe: 'מדד הפחד VIX',
    descriptionHe: 'התנודתיות הצפויה במדד S&P 500 ל־30 הימים הקרובים',
    provider: 'TradingView Israel',
    url: 'https://il.tradingview.com/symbols/CBOE-VIX/',
    icon: '🌡️',
    category: 'volatility',
    external: true,
    canonicalIdentity: 'VIX',
    aliases: Object.freeze(['VIX']),
  }),
  Object.freeze({
    key: 'dxy',
    labelHe: 'מדד הדולר DXY',
    descriptionHe: 'עוצמת הדולר האמריקאי מול סל מטבעות מרכזיים',
    provider: 'TradingView Israel',
    url: 'https://il.tradingview.com/symbols/TVC-DXY/',
    icon: '💵',
    category: 'currency',
    external: true,
    canonicalIdentity: 'DOLLAR',
    aliases: Object.freeze(['DOLLAR', 'DXY']),
  }),
  Object.freeze({
    key: 'wti',
    labelHe: 'נפט WTI',
    descriptionHe: 'מחיר ומגמת הנפט הגולמי מסוג WTI',
    provider: 'TradingView Israel',
    url: 'https://il.tradingview.com/symbols/USOIL/',
    icon: '🛢️',
    category: 'commodity',
    external: true,
    canonicalIdentity: 'OIL',
    aliases: Object.freeze(['OIL', 'WTI']),
  }),
]);

export const SPECIALIZED_SECTION_RESOURCES = Object.freeze({
  news: Object.freeze([
    {
      key: 'all-news',
      labelHe: 'כל החדשות',
      url: `${INVESTING_IL}/news`,
      provider: 'Investing.com Israel',
      tooltipHe: 'פתח את מרכז החדשות ב־Investing ישראל',
    },
    {
      key: 'headlines',
      labelHe: 'מבזקים',
      url: `${INVESTING_IL}/news/headlines`,
      provider: 'Investing.com Israel',
      tooltipHe: 'פתח מבזקי חדשות ב־Investing ישראל',
    },
    {
      key: 'stock-market-news',
      labelHe: 'שוק המניות',
      url: `${INVESTING_IL}/news/stock-market-news`,
      provider: 'Investing.com Israel',
      tooltipHe: 'פתח חדשות שוק המניות ב־Investing ישראל',
    },
    {
      key: 'economy',
      labelHe: 'כלכלה',
      url: `${INVESTING_IL}/news/economy`,
      provider: 'Investing.com Israel',
      tooltipHe: 'פתח חדשות כלכלה ב־Investing ישראל',
    },
  ]),
  'economic-calendar': Object.freeze([
    {
      key: 'economic-calendar',
      labelHe: 'יומן כלכלי',
      url: `${INVESTING_IL}/economic-calendar`,
      provider: 'Investing.com Israel',
      tooltipHe: 'פתח את יומן האירועים הכלכלי ב־Investing ישראל',
    },
    {
      key: 'fed-rate',
      labelHe: 'ריבית הפד',
      url: `${INVESTING_IL}/central-banks/fed-rate-monitor`,
      provider: 'Investing.com Israel',
      tooltipHe: 'פתח את כלי ניטור ריבית הפד ב־Investing ישראל',
    },
  ]),
  macro: Object.freeze([
    {
      key: 'economy-news',
      labelHe: 'חדשות כלכלה',
      url: `${INVESTING_IL}/news/economy`,
      provider: 'Investing.com Israel',
      tooltipHe: 'פתח חדשות כלכלה ומאקרו ב־Investing ישראל',
    },
    {
      key: 'us-10y',
      labelHe: 'אג״ח 10Y',
      url: `${INVESTING_IL}/rates-bonds/u.s.-10-year-bond-yield`,
      provider: 'Investing.com Israel',
      tooltipHe: 'פתח את תשואת אג״ח ארצות הברית ל־10 שנים ב־Investing ישראל',
    },
    {
      key: 'fed-rate',
      labelHe: 'ריבית הפד',
      url: `${INVESTING_IL}/central-banks/fed-rate-monitor`,
      provider: 'Investing.com Israel',
      tooltipHe: 'פתח את כלי ניטור ריבית הפד ב־Investing ישראל',
    },
    {
      key: 'wti-oil',
      labelHe: 'נפט WTI',
      url: `${INVESTING_IL}/commodities/crude-oil`,
      provider: 'Investing.com Israel',
      tooltipHe: 'פתח נתוני נפט WTI ב־Investing ישראל',
    },
  ]),
  sentiment: Object.freeze([
    { key: 'fear-greed', labelHe: 'פחד ותאווה', url: 'https://www.cnn.com/markets/fear-and-greed', provider: 'CNN', tooltipHe: 'פתח מדד סנטימנט משולב של פחד ותאווה ב־CNN' },
    { key: 'retail-investors', labelHe: 'משקיעים פרטיים', url: 'https://www.aaii.com/sentimentsurvey', provider: 'AAII', tooltipHe: 'פתח את סקר הסנטימנט השבועי של משקיעים פרטיים ב־AAII' },
    { key: 'active-managers', labelHe: 'מנהלי השקעות', url: 'https://www.naaim.org/programs/naaim-exposure-index/', provider: 'NAAIM', tooltipHe: 'פתח את מדד החשיפה השבועי של מנהלי השקעות ב־NAAIM' },
    { key: 'put-call', labelHe: 'Put/Call', url: 'https://www.cboe.com/us/options/market_statistics/daily/', provider: 'Cboe', tooltipHe: 'פתח נתוני פעילות אופציות יומיים ב־Cboe' },
    { key: 'vix', labelHe: 'VIX', url: 'https://www.cboe.com/tradable_products/vix/', provider: 'Cboe', tooltipHe: 'פתח מידע רשמי על מדד ציפיות התנודתיות VIX ב־Cboe' },
    { key: 'sector-map', labelHe: 'מפת סקטורים', url: 'https://finviz.com/groups.ashx', provider: 'Finviz', tooltipHe: 'פתח את מפת ביצועי הסקטורים ב־Finviz' },
  ]),
  sectors: Object.freeze([
    {
      key: 'sector-overview',
      labelHe: 'מפות סקטורים',
      url: 'https://finviz.com/map?t=sec',
      provider: 'Finviz',
      group: 'research',
      tooltipHe: 'פתח מפת סקטורים חזותית ב־Finviz',
      ariaLabelHe: 'פתח את מפת הסקטורים באתר Finviz',
      external: true,
    },
    { key: 'sector-groups', labelHe: 'טבלת סקטורים', url: 'https://finviz.com/groups', provider: 'Finviz', group: 'research', tooltipHe: 'פתח טבלת קבוצות וסקטורים ב־Finviz', ariaLabelHe: 'פתח את טבלת הסקטורים באתר Finviz', external: true },
    { key: 'sector-heatmap', labelHe: 'מפת חום', url: 'https://www.tradingview.com/heatmap/stock/', provider: 'TradingView', group: 'research', tooltipHe: 'פתח מפת חום של שוק המניות ב־TradingView', ariaLabelHe: 'פתח את מפת החום של שוק המניות באתר TradingView', external: true },
    { key: 'sector-etf-tracker', labelHe: 'תעודות סל', url: 'https://www.ssga.com/us/en/intermediary/resources/sector-tracker', provider: 'State Street', group: 'research', tooltipHe: 'פתח כלי מעקב רשמי אחר תעודות סל סקטוריאליות של State Street', ariaLabelHe: 'פתח את כלי המעקב אחר תעודות סל סקטוריאליות באתר State Street', external: true },
    {
      key: 'sector-performance-daily',
      labelHe: 'יומי',
      url: 'https://finviz.com/groups?g=sector&o=-change&v=140',
      provider: 'Finviz',
      group: 'performance',
      period: 'daily',
      descriptionHe: 'ביצועי היום, מהחזק לחלש',
      tooltipHe: 'סקטורים לפי ביצועי היום, מהחזק לחלש',
      ariaLabelHe: 'פתח את דירוג הסקטורים היומי באתר Finviz',
      external: true,
    },
    {
      key: 'sector-performance-weekly',
      labelHe: 'שבועי',
      url: 'https://finviz.com/groups?g=sector&o=-perf1w&v=140',
      provider: 'Finviz',
      group: 'performance',
      period: 'weekly',
      descriptionHe: 'ביצועי השבוע, מהחזק לחלש',
      tooltipHe: 'סקטורים לפי ביצועי השבוע, מהחזק לחלש',
      ariaLabelHe: 'פתח את דירוג הסקטורים השבועי באתר Finviz',
      external: true,
    },
    {
      key: 'sector-performance-monthly',
      labelHe: 'חודשי',
      url: 'https://finviz.com/groups?g=sector&o=-perf4w&v=140',
      provider: 'Finviz',
      group: 'performance',
      period: 'four-weeks',
      descriptionHe: 'ביצועי ארבעת השבועות האחרונים, מהחזק לחלש',
      tooltipHe: 'סקטורים לפי ביצועי ארבעת השבועות האחרונים, מהחזק לחלש',
      ariaLabelHe: 'פתח את דירוג הסקטורים לארבעת השבועות האחרונים באתר Finviz',
      external: true,
    },
    {
      key: 'sector-technicals-info',
      labelHe: 'ניתוח טכני',
      provider: 'TradingView',
      group: 'performance',
      kind: 'info',
      tooltipHe: 'הסבר על קישורי RSI וניתוח טכני בשורות הסקטורים',
      ariaLabelHe: 'הצג הסבר על RSI וניתוח טכני לסקטורים',
      detailHe: 'קישור טכני מוצג רק כאשר הסקטור מזוהה באופן קנוני או כאשר סופק ETF מפורש שכבר אומת. הקישור פותח את דף הניתוח הטכני של ה־ETF ב־TradingView; האפליקציה אינה ממציאה קישור לסקטור לא מזוהה.',
      external: false,
    },
  ]),
  'stocks-mentioned': Object.freeze([
    {
      key: 'gainers',
      labelHe: 'עולות',
      url: 'https://finviz.com/screener?s=ta_topgainers&v=111',
      provider: 'Finviz',
      tooltipHe: 'פתח את רשימת המניות העולות ב־Finviz',
      ariaLabelHe: 'פתח את רשימת המניות העולות המובילות באתר Finviz',
    },
    {
      key: 'losers',
      labelHe: 'יורדות',
      url: 'https://finviz.com/screener?s=ta_toplosers&v=111',
      provider: 'Finviz',
      tooltipHe: 'פתח את רשימת המניות היורדות ב־Finviz',
      ariaLabelHe: 'פתח את רשימת המניות היורדות המובילות באתר Finviz',
    },
  ]),
  markets: Object.freeze([
    {
      key: 'market-map',
      labelHe: 'מפת השוק',
      url: 'https://finviz.com/map?t=sec_all',
      provider: 'Finviz',
      tooltipHe: 'פתח את מפת המניות והסקטורים ב־Finviz',
      ariaLabelHe: 'פתח את מפת שוק המניות והסקטורים באתר Finviz',
    },
    {
      key: 'futures',
      labelHe: 'חוזים',
      url: 'https://finviz.com/futures',
      provider: 'Finviz',
      tooltipHe: 'פתח את מסך החוזים העתידיים ב־Finviz',
      ariaLabelHe: 'פתח את נתוני החוזים העתידיים באתר Finviz',
    },
    {
      key: 'world-indices',
      labelHe: 'מדדים בעולם',
      url: `${INVESTING_IL}/indices/major-indices`,
      provider: 'Investing.com Israel',
      tooltipHe: 'פתח את רשימת המדדים המובילים בעולם ב־Investing ישראל',
      ariaLabelHe: 'פתח את נתוני המדדים המובילים בעולם באתר Investing ישראל',
    },
  ]),
});

export function getSpecializedSectionResources(sectionKey) {
  return SPECIALIZED_SECTION_RESOURCES[sectionKey] || [];
}

export function getMacroResearchResources() {
  return MACRO_RESEARCH_RESOURCES;
}

export function getMacroResearchResourceForIndicator(value) {
  const normalized = String(value ?? '').trim().toUpperCase();
  if (!normalized) return null;
  return MACRO_RESEARCH_RESOURCES.find((resource) => resource.aliases?.includes(normalized)) || null;
}
