// generateSummary — Generates AI summary from video transcript
//
// Expected request body:
// { transcript: string, title: string }
//
// Returns:
// { shortSummary, fullSummary, keyPoints[], tags[] }

Deno.serve(async (req) => {
  if (req.method !== "POST") {
    return new Response(
      JSON.stringify({ error: "Method not allowed" }),
      { status: 405, headers: { "Content-Type": "application/json" } }
    );
  }

  try {
    const { transcript, title } = await req.json();

    if (!transcript) {
      return new Response(
        JSON.stringify({ error: "Missing required field: transcript" }),
        { status: 400, headers: { "Content-Type": "application/json" } }
      );
    }

    // TODO: Integrate with AI API (Claude/OpenAI)
    // The prompt should request:
    // 1. shortSummary — 1-2 sentences
    // 2. fullSummary — detailed paragraph
    // 3. keyPoints — array of 3-5 key takeaways
    // 4. tags — array of relevant topic tags

    return new Response(
      JSON.stringify({
        shortSummary: `Summary placeholder for: ${title}`,
        fullSummary: "Full summary will be generated by AI integration.",
        keyPoints: ["Key point 1", "Key point 2", "Key point 3"],
        tags: ["placeholder"],
      }),
      { status: 200, headers: { "Content-Type": "application/json" } }
    );
  } catch (error) {
    return new Response(
      JSON.stringify({ error: error.message }),
      { status: 500, headers: { "Content-Type": "application/json" } }
    );
  }
});
